---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: slack
  namespace: flux-system
spec:
  providerRef:
    name: slack
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: '*'
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: rpi-apps
  namespace: flux-system
spec:
  providerRef:
    name: rpi-apps
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: '*'
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: rpi-infra
  namespace: flux-system
spec:
  providerRef:
    name: rpi-infra
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: '*'