---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openfaas
  namespace: openfaas
spec:
  releaseName: openfaas
  chart:
    spec:
      chart: openfaas
      version: 9.0.2
      sourceRef:
        kind: HelmRepository
        name: openfaas
        namespace: openfaas
  interval: 1m0s
  values:
    generateBasicAuth: true
    serviceType: LoadBalancer
    nodeSelector:
      beta.kubernetes.io/arch: arm64
    basic_auth: true
    clusterRole: true
    createCRDs: true
    openfaasPRO: false
    gateway:
      directFunctions: true
      replicas: 3
    oidcAuthPlugin:
      enabled: false
    operator:
      create: true
    queueWorker:
      replicas: 3
    prometheus:
      resources:
        requests:
          memory: "100Mi"
    faasIdler:
      replicas: 1
    basicAuthPlugin:
      replicas: 1
    ingressOperator:
      create: false
    nats:
      metrics:
        # Should stay off by default because the exporter is not multi-arch (yet)
        enabled: false