---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openfaas
  namespace: openfaas
spec:
  releaseName: openfaas
  chart:
    spec:
      chart: openfaas
      version: 7.0.3
      sourceRef:
        kind: HelmRepository
        name: openfaas
        namespace: openfaas
  interval: 1m0s
  values:
    generateBasicAuth: true
    serviceType: LoadBalancer
    nodeSelector:
      beta.kubernetes.io/arch: arm64
    basic_auth: true
    clusterRole: true
    createCRDs: true
    # See https://www.openfaas.com/support for more
    openfaasPRO: false
    gateway:
      image: openfaas/gateway:0.20.1-arm64
      directFunctions: true
      replicas: 3
    oidcAuthPlugin:
      enabled: false
    faasnetes:
      image: ghcr.io/openfaas/faas-netes:0.12.13
    operator:
      image: ghcr.io/openfaas/faas-netes:0.12.13
      create: true
    queueWorker:
      image: openfaas/queue-worker:0.11.2
      replicas: 3
    prometheus:
      image: prom/prometheus:v2.11.0
      resources:
        requests:
          memory: "100Mi"
    alertmanager:
      image: prom/alertmanager:v0.18.0
    faasIdler:
      replicas: 1
      image: ghcr.io/openfaas/faas-idler-pro:0.5.0
    basicAuthPlugin:
      image: openfaas/basic-auth-plugin:0.20.1-arm64
      replicas: 1
    ingressOperator:
      create: false

    # Unfortunately the exporter is not multi-arch (yet)
    nats:
      metrics:
        enabled: false