apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: etcd-backup
  namespace: kube-system
spec:
  schedule: "0 0 1-31/2 * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          hostNetwork: true
          nodeName: rp0
          tolerations:
          - key: node-role.kubernetes.io/control-plane
            effect: NoSchedule
          volumes:
          - name: tmp
            emptyDir: {}
          - name: kubernetes
            hostPath:
              path: /etc/kubernetes
              type: Directory
          - name: secret
            secret:
              secretName: rpi-etcd-backup-service-account
          initContainers:
          - name: etcd
            image: k8s.gcr.io/etcd:3.4.13-0
            imagePullPolicy: IfNotPresent
            command:
            - etcdctl
            args:
            - --cert=/etc/kubernetes/pki/etcd/peer.crt
            - --key=/etc/kubernetes/pki/etcd/peer.key
            - --cacert=/etc/kubernetes/pki/etcd/ca.crt
            - --endpoints=https://10.1.10.240:2379
            - snapshot
            - save
            - /tmp/backup.db
            volumeMounts:
            - mountPath: /etc/kubernetes
              name: kubernetes
              readOnly: true
            - name: tmp
              mountPath: "/tmp"
          containers:
          - name: backup
            image: sthlmio/go-gs-backup:1.0.5 # {"$imagepolicy": "flux-system:sthlmio-go-gs-backup"}
            imagePullPolicy: IfNotPresent
            env:
            - name: BUCKET_NAME
              value: "rpi-kubeadm-backup"
            - name: LOCAL_OBJECT_PATH
              value: "/tmp/backup.db"
            - name: REMOTE_OBJECT_PATH
              value: "etcd/backup.db"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/etc/secret/sthlmio.json"
            volumeMounts:
            - name: tmp
              mountPath: /tmp
              readOnly: true
            - name: secret
              mountPath: /etc/secret
              readOnly: true
