---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: etcd-defrag
  namespace: kube-system
spec:
  schedule: "0 0 1-31/2 * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          hostNetwork: true
          nodeName: rp0
          tolerations:
          - key: node-role.kubernetes.io/master
            effect: NoSchedule
          volumes:
          - hostPath:
              path: /etc/kubernetes
              type: Directory
            name: kubernetes
          containers:
          - name: etcd
            image: k8s.gcr.io/etcd:3.4.13-0
            imagePullPolicy: IfNotPresent
            command:
              - etcdctl
              - --cert /etc/kubernetes/pki/etcd/peer.crt
              - --key /etc/kubernetes/pki/etcd/peer.key
              - --cacert /etc/kubernetes/pki/etcd/ca.crt
              - --endpoints https://10.1.10.240:2379
              - defrag
            volumeMounts:
            - mountPath: /etc/kubernetes
              name: kubernetes
              readOnly: true