proxyInjector:
  externalSecret: true
  caBundle: |
    -----BEGIN CERTIFICATE-----
    MIIBkjCCATmgAwIBAgIQd6zCyZsj5ZKFqFt+Fi0YxDAKBggqhkjOPQQDAjAoMSYw
    JAYDVQQDEx13ZWJob29rLmxpbmtlcmQuY2x1c3Rlci5sb2NhbDAeFw0yMDEyMDQy
    MDA1NDNaFw0zMDEyMDIyMDA1NDNaMCgxJjAkBgNVBAMTHXdlYmhvb2subGlua2Vy
    ZC5jbHVzdGVyLmxvY2FsMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEKJsBWdQK
    SitPHVwe4cTVIYbGqT0XCVarnkNMNUkqqH7ylp/+w5/9KNdGMDb1G3xNG5fGxld1
    JXdLNHc52wwrC6NFMEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8C
    AQEwHQYDVR0OBBYEFJlrEwmKjOCnTzQ5OxP8qtUqj6n+MAoGCCqGSM49BAMCA0cA
    MEQCIGD6Bckk6mGutKnZFMqrraegS0XuQxDsqnPgYSdBg+sVAiBYvbJu6Hyeqj2c
    45+PBDFpLjnvtqd3l+0YOt8H1uOUvw==
    -----END CERTIFICATE-----
profileValidator:
  externalSecret: true
  caBundle: |
    -----BEGIN CERTIFICATE-----
    MIIBkjCCATmgAwIBAgIQd6zCyZsj5ZKFqFt+Fi0YxDAKBggqhkjOPQQDAjAoMSYw
    JAYDVQQDEx13ZWJob29rLmxpbmtlcmQuY2x1c3Rlci5sb2NhbDAeFw0yMDEyMDQy
    MDA1NDNaFw0zMDEyMDIyMDA1NDNaMCgxJjAkBgNVBAMTHXdlYmhvb2subGlua2Vy
    ZC5jbHVzdGVyLmxvY2FsMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEKJsBWdQK
    SitPHVwe4cTVIYbGqT0XCVarnkNMNUkqqH7ylp/+w5/9KNdGMDb1G3xNG5fGxld1
    JXdLNHc52wwrC6NFMEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8C
    AQEwHQYDVR0OBBYEFJlrEwmKjOCnTzQ5OxP8qtUqj6n+MAoGCCqGSM49BAMCA0cA
    MEQCIGD6Bckk6mGutKnZFMqrraegS0XuQxDsqnPgYSdBg+sVAiBYvbJu6Hyeqj2c
    45+PBDFpLjnvtqd3l+0YOt8H1uOUvw==
    -----END CERTIFICATE-----
tap:
  externalSecret: true
  caBundle: |
    -----BEGIN CERTIFICATE-----
    MIIBkjCCATmgAwIBAgIQd6zCyZsj5ZKFqFt+Fi0YxDAKBggqhkjOPQQDAjAoMSYw
    JAYDVQQDEx13ZWJob29rLmxpbmtlcmQuY2x1c3Rlci5sb2NhbDAeFw0yMDEyMDQy
    MDA1NDNaFw0zMDEyMDIyMDA1NDNaMCgxJjAkBgNVBAMTHXdlYmhvb2subGlua2Vy
    ZC5jbHVzdGVyLmxvY2FsMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEKJsBWdQK
    SitPHVwe4cTVIYbGqT0XCVarnkNMNUkqqH7ylp/+w5/9KNdGMDb1G3xNG5fGxld1
    JXdLNHc52wwrC6NFMEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8C
    AQEwHQYDVR0OBBYEFJlrEwmKjOCnTzQ5OxP8qtUqj6n+MAoGCCqGSM49BAMCA0cA
    MEQCIGD6Bckk6mGutKnZFMqrraegS0XuQxDsqnPgYSdBg+sVAiBYvbJu6Hyeqj2c
    45+PBDFpLjnvtqd3l+0YOt8H1uOUvw==
    -----END CERTIFICATE-----
