apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./certificates.yaml
- ./components.yaml
- ./issuers.yaml
- ./linkerd-trust-anchor.yaml
- ./webhook-trust-anchor.yaml
- ./viz.yaml
