---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  releaseName: grafana
  chart:
    spec:
      chart: grafana
      version: 6.34.0
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
  interval: 1m0s
  values:
    admin:
      existingSecret: grafana-credentials
      userKey: admin-user
      passwordKey: admin-password
    deploymentStrategy:
      type: Recreate
    service:
      type: LoadBalancer
    plugins:
      - grafana-piechart-panel
    sidecar:
      dashboards:
        enabled: true
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
        - name: Prometheus
          type: prometheus
          url: http://prometheus-server.monitoring.svc.cluster.local
        - name: Prometheus (linkerd)
          type: prometheus
          url: http://prometheus.linkerd-viz.svc.cluster.local:9090