---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  releaseName: prometheus
  chart:
    spec:
      chart: prometheus
      version: 13.2.1
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
  interval: 1m0s
  values:
    nodeExporter:
      enabled: false
    kubeStateMetrics:
      enabled: false
    server:
      strategy:
        type: Recreate
      retention: "7d"
      global:
        scrape_interval: 10s
        scrape_timeout: 8s
      persistentVolume:
        storageClass: rook-ceph-block
    alertmanager:
      persistentVolume:
        storageClass: rook-ceph-block
    extraScrapeConfigs: |
      - job_name: etcd
        static_configs:
          - targets: ['10.1.10.240:2381']
      - job_name: traefik
        static_configs:
          - targets: ['traefik.traefik.svc.cluster.local:8082']
      - job_name: node
        static_configs:
          - targets: ['10.1.10.240:9100', '10.1.10.241:9100', '10.1.10.242:9100', '10.1.10.243:9100', '10.1.10.244:9100']
    # kube-state-metrics:
    #   image:
    #     repository: k8s.gcr.io/kube-state-metrics/kube-state-metrics
    #     tag: v2.0.0-beta
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  releaseName: grafana
  chart:
    spec:
      chart: grafana
      version: 6.2.0
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
  interval: 1m0s
  values:
    admin:
      existingSecret: grafana-credentials
      userKey: admin-user
      passwordKey: admin-password
    deploymentStrategy:
      type: Recreate
    service:
      type: LoadBalancer
    plugins:
      - grafana-piechart-panel
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
        - name: Prometheus
          type: prometheus
          url: http://prometheus-server.monitoring.svc.cluster.local
    persistence:
      enabled: true
      size: 5Gi
      storageClassName: rook-ceph-block