apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCGW+1NlU/krl6nsRymbDszawR5kW6c3oQb9yVO24n2O6SLGyYp1ICD/4GHHYF4An6ZT8RuVec4U411pp+M8lU5gC+pV+ZJdd6m1puIcNPVTa85B7AcIaXPUuJOeM5G7uTUU3X3I+3NqTYTs0/8J3wLTs5glJ6F7vw11yIGac2x1KxqW2yNlZ9me5Lzs039QOW/8i0Hr7ZBXhzBPvaLxEvYodD85W0OtmfN1ZroJS9xw+o1+DnJd8u/HOy1FNWdMx56njutUjExrqcGLIc+CDq6XpI4kLOGldKd9RHm+UdUI4bOxISkhFco+xmFD7fD+LEGxjMmmmnQRSk6hEbygVqX480lO9/fclmNgb77gwYrOb+pxAHg/p6ucPATHPkTlWtUDvzwILnSh9idRl4ATWHrlW+Fq+tqjQcMVTdIOK7HiGNK+epJGl5z2djp6k43JtqAjWnKUJbI3QLeg8IP+L7MvWOZNiHCwVWVXTxlkM7kao0OLM3qiPBWIXADb16l2uo2gV1QW3DwRG7kkd3PosH3EM3AXiWAcLzQRfKB+efZXaB/kWBaMuYVj480TEiBRUMQdDB6C3uBtFUOv8z2iZK/1194tbutYKHTBoo5KQ+HHRghuD966kBGBo0iaiTMktQa8TqeQubdTTBvY7H5QWqsQvNABI+iUj+4+Qd299luUWPyu1nzLGbSjDlk2qdSK/WqDp3MCnjZOazb6YadwC+M29h1UbEATKkPgHJusfsUdA==
    admin-user: AgA7laU3cnPs5e03W3zUktmQq3jS9qmA7wWOFxKmpP79/+lUtrltOGT3WGuwTuXuE5WE9VkG+N+OHLTvl6ADEDmSr2TmxXZNQDN75caUlS9XOhexQDuZHpCCh774BtCBSVEpcGa+0RvHBzjc3RgB2Lh3QFhlOl5XMjPIa5Cn/XkXqKQcU56FvtSjp/Qke7/cwj1DDr44lTN53AQ7kt+9Zyu61leG9cLwcfZQqpKDpcLiVoffGYAf8PopoemOnQpUSS9jRqRM24AOhWuhr3Kq0d/o9BIZuxk01Ospr8zZpLmVpi3CWgKA9Tc6a6B2ByEmPayr5+Mq4Jm6mhR8E2I+cUtpqYYWd9JPVzzM71pZZ1RKwagUwglNffaqg+VISabON5vgZ0+40TzTw8I/ozVQEWwj/cgmUzDEyHTbROTMmyPah9rgiZlP7aqhSqrkxA0kx69VYcXs4dH9f0Huu+RHTqG+qrbZl5b0P3BOwx079S5rJjKXTZju55bvUQEe75T9FZ0hTDb7fyVsnS1YkDQfKw3VkgKW9G4Ia4kWZlPCCxJ9l/E9jd7o7vhDil0ko4PakCGNvEpzF+UP/l70hcgMR41XHr357wzdZMJpmyevRR+B2XYBwtaciRJaqDFN3zSE1ZMEvQkYVoJ3c1/EoXdYyQG9oLNOhhZgSToBmXKpzrkyeRKelpTmq6djCRK3YXuLlLSzNrf19A==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-credentials
      namespace: monitoring

