apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgB/dT/wfdSLrHXU6I8PLZBgmd6nq2Sp5cZceH869wiLd6ToHUWscmRhZU5oDlfU8lh4yefiBxpyvEIYWnffQG9S9Kq176CaO3JEjwWr2AuL4+MAvRFXa4vLNg4adnwrty0YFuBh37dqblv7Z1OV+TC9TXEfKMdyDCpK/yT0OU1gyPYVTG1PuVMnThRFEx5+KGxWkZpiSJTdVoFaiI4xBuFgG8pVyHdF4bvmxL8xxi1rkizE80h+zfvAop6VazJns8L+IgoYmTzia+soxd1OWQNPwSnyROnhhQg9ZWCSX5R/QUbI8CBkD8ay44uod9CKu8FOzwnTv2HfKNHFt1FzBd7hnXUrcp6BiqGlq/zWgZBzqy4KwPIOUTq/FPW/KrhIWkPSMXNYzx2BmPDnUbOzE7Rc8f9bv7rwLX0aB8bxl7Y9xeeAR3UtnaCmTEK+qX+DOFJTr/YMpDElYXdv+183egR45XIWlDwlZTjo2cogXOQdEA+C0dCu4Knghunxie520r8gNE1STwV054Yvpi+6if3lIVAGwU1p56IVt4SSjxmupx69BnyxLT8XeZU9NjoCrgncI7MiZdSxic8Np78O6+zjbztYqmGMBKXDEDJ85oby9scD1UZxMKpIQhRS4j1K4vy10AW6mVSy9Cmjijn552Mpo/k2eqHma7q84vaj7YIbAF3oP1C7K46WHh2I0CRz9YhhX8BDXsSjVfcPLqvmRdvm1DfcqPk5/vaNctWll8xvj5UqAAIi6KkT
    admin-user: AgCFxfQu/DIStjMe/UYhMkcpxWm68VlMjdFurpCY0hZZxHbhJl4HsVsb9Lg6XpUN3vU3G+rK1Mvm9r1E/VHtrv5Lz74am735sIAm7n0IzI45hW2lGHmSqia+SFnoDdHKb6ZYtfJPCL6+jW18EJpKhd48FypV/UsVw3cA/QLRKew6zZev7Be5rUDK00CRor22EwVDPhOaVifAZW6J3o/tq5UscGQ6ZjvsHCaaEmvejlMWztg5xKDv4LlPJbUVJXJxz7whUHvDfWTbUyHGJ7qq+3AVLmRmbiA1GZ2ddO/HsZ7QTMxtiOjiWW1hWY0E8v4Gx6wDiY4sYmfn7ZIZy/22Kzzyg5pU7cXbGlXL0TfPTHSRFwxdPp9nn2qgnie7TlZOa2KzsWh120dh8NXoc9VrgcZARqmeVkyL7zPmVzHjALyHp/aGp9khkZHPSieS3goiJZmLfZDWmRP5sAG9KtO+TMAjUxSbEztXSgQinb+HJW8KDWMxBbUCOER9SMfcpWMZ+yZrQbX6IuoJbuZBgjeXcFl3uA59sRchbTTTDrLc7E1+bM0NiaRtTV4+KoN1NSlVtvd3yl0jkira+UgnbX6uOlXH9qSCC/xPJVnMSK5UV0ilyY6YtvtkL/TJnRq3D6XM/6Qplkc2ysaikeHnkYJ14iNblZF/IN4bbfl+b5mxvMgbqkE+Mav4VULvG/BCB99saQoprVwoiA==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-credentials
      namespace: monitoring

