apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: memberlist
  namespace: metallb-system
spec:
  encryptedData:
    secretkey: AgCqGu2OoategRYtX7L8VHq08DTMhPvA0yn2kbRrLfVOje2ILPkkSBSA3p2Xkck4todQ3tltN15O16kDe8TzbpZsFqd9f5OxlYrPzI8ZHE2rFFqrlJN+l8RvstmvpyL3nrK4Ek0M3ARGiZsfg7huYir1OFjxBOXJ7AMRRYdlxG/R/iSsz5bXh4x0UuK1ScCrb+4JlgjiVvUGjnHII6I4DoFuwDTX2i9yjf19r5BaLsKbQ18uzuVEQn/8rYbW49GeLcSh95ptnEqlW6BsgmNvcLUx9BfQ8tu1jRZDw8cJoRuNuMT4kFpxVPyLstaUZ+TEe3GoFgyhFSy97/oy6EiEPditLuOauKLSeg3j+ViCkOzKJa2xTbIkb377FEp6Doa25wCno02IcfMKJQBknh929LFzGhKwprNtSVIVv3NtByi6Or+okS4jCLFhN8S4d3ASyhDJdnd5I7mu5my7aZzFRWFDj0TvvVpxvth3pREBUMlKbxBL5M2c6BuE5gdjOgmH5H4/Yqnz4w75rz4YTU5oDknYs2QQriLS+nXy8JiJma5C2hs3Y2/ZA6nVDcB9W/sqbJsQyzvuuiXrww2cm73K6B5PBa5cyufeDxnY461lGuDirTstzQkdqRnMrBRuO69PSsE63bKvMsymEP6MRKpRSIf7ufMQdS/NhCb8Foe9FcKwtqgJpdiEr9+0SabD5NUN0evydGglg8qIRggDKY0mYPYbm5ieUQ4qGHXFEc0f2H5rQ44btw08fomXtzIYv9wredoVa0+ombTjOiMLR5mSFmjlTkB41SU/y3Ww0i6VvbfHIhmfKWFIykKvVEVRBIK7Cu77LrDCtupNK1hO6JoHysYHncupY2gHxzOaqgKr0INYqJuud+sC6aH31Rzy6qTxTi+3A/Sc3saVasz6keo7dk643GSxy60QPIPf9T5JCfk=
  template:
    metadata:
      creationTimestamp: null
      name: memberlist
      namespace: metallb-system

