apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: memberlist
  namespace: metallb-system
spec:
  encryptedData:
    secretkey: AgACcBkPWKr0IpNIsP2akwZA6r1AnhD9Xy9CrHjB+vOBcAXiiyc1E0CBvHLtS6XvqAo91U69fOIbNknGVukJjc9wUiUkDpRwL9SWJBRGgyGE5IwP9JK4tyDT1D96LwZCYrpgilpIni9qLBc1RcTZ0GvcrAjbjs0lYaT2g9eieWAvF/OWKbYEaWwypz2KLWISmfTTd+4eUU9MboMs7vDtJaGV3EiTPq6nu2oURrqaoC/Qra3OAd3ITgCDEyZo/hmP1BN6T0Di8xSifCgtbAHJYyH3ML+fWsXzBnFxZ9Hj/gkGCm5i2lOEJtC9lMt6lY7/O0y7AKjSE3o7q2X5bzdeHLgsE1k7zhV4kz0yJJMkLKkKEqcIncuU3bnWmgtyrP5lPy+Z/oF+cyxC4m/pRuEnwMQGbkqwUUlNiCwfIkxSAOkl4ni4zW+0Z2DUzICeSSFmV/zXY+B1chg2tHYCB9bVU/hR26Mh1dc+hVmyHLzTSMBjYwLYCSsnOHWjb64mWs7QsuA7nsziu1+4r+F9a0ub+qrJHVz6ySAtIeKMWbrR6WTl7tTVjZnGtK8OV2URBySQPcMYwyD2apPUYW2WKzMFTMAdrGceZnDYKcg8+X+lfj3bC+u/83VFQMsahGmO/zV7whQjsHxrzLqnVj6jea5BLBuRnBcVkWRyHMxxfWSH96r29bmx5K3bjfx5UNQv2cKTrw5pv5iDPsr+GKqaca3KRYCWo0AKLHA83sFM+Vz/60jCxlWM7eh776E4fmdw41CPPPeru5KrttSriRmfVT+IV7J+P2ljFeqY+BjPlnaadFuctky10N+0oZ1eEFWwZHTVs4khXjduCHZiEmscjkXTDzHUjEv46tV9O0CyzxUVRBGYtiO4cVnR9YczGtnbHoZXFGcY94d+wZdGNhyTN8rWA3UH93658P7cxpgtXUnhNcM=
  template:
    metadata:
      creationTimestamp: null
      name: memberlist
      namespace: metallb-system

