---
apiVersion: v1
kind: ConfigMap
metadata:
  name: contour
  namespace: projectcontour
data:
  contour.yaml: |
    # Disable HTTPProxy permitInsecure field
    disablePermitInsecure: false

    tls:
      # minimum TLS version that Contour will negotiate
      minimum-protocol-version: "1.2"
      fallback-certificate:
      envoy-client-certificate:

    ### Logging options
    # Default setting
    accesslog-format: envoy

    # Global Policy settings.
    policy:
      # Default headers to set on all requests (unless set/removed on the HTTPProxy object itself)
      request-headers:
        set:
          l5d-dst-override: "%CONTOUR_SERVICE_NAME%.%CONTOUR_NAMESPACE%.svc.cluster.local:%CONTOUR_SERVICE_PORT%"
      # Default headers to set on all responses (unless set/removed on the HTTPProxy object itself)
      response-headers:
        set:
          Strict-Transport-Security: max-age=31536000; includeSubDomains
          X-Content-Type-Options: nosniff
          X-Frame-Options: DENY
          X-XSS-Protection: 1; mode=block
    
