---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: contour
  name: contour
  namespace: projectcontour
spec:
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled