---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: contour
  namespace: contour
spec:
  releaseName: contour
  chart:
    spec:
      chart: contour
      version: 7.3.3
      sourceRef:
        kind: HelmRepository
        name: contour
        namespace: contour
  interval: 1m0s
  values:
    contour:
      replicaCount: 3
      service:
        type: LoadBalancer
        externalTrafficPolicy: Local
        loadBalancerIP: 192.168.2.3
      ingressClass:
        name: contour
        create: false
        default: false