apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./components.yaml
patchesStrategicMerge:
- ./envoy-linkerd.yaml
- ./contour-deployment.yaml
- ./envoy-service.yaml
- ./configmap.yaml
