---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cluster-issuer-cloudflare-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: fredrik@sthlm.io
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          cloudflare:
            email: fredrik@sthlm.io
            apiKeySecretRef:
              name: cluster-issuer-cloudflare
              key: cloudflare_api_key