---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  releaseName: cert-manager
  chart:
    spec:
      chart: cert-manager
      version: v1.1.0
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: cert-manager
  interval: 1m0s
  values:
    installCRDs: true
    image:
      repository: quay.io/jetstack/cert-manager-controller-arm64
    cainjector:
      image:
        repository: quay.io/jetstack/cert-manager-cainjector-arm64
    webhook:
      image:
        repository: quay.io/jetstack/cert-manager-webhook-arm64