---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  releaseName: cert-manager
  chart:
    spec:
      chart: cert-manager
      version: v1.5.4
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: cert-manager
  interval: 1m0s
  values:
    installCRDs: true